import type { Assessment } from "../types.js";

export interface GeneratedDoc {
  filename: string;
  content: string;
}

const FOOTER =
  "\n\n---\n_Starter template generated by sentinel-act. Fill the [TODO] fields and have qualified counsel review before relying on it. Not legal advice._\n";

/** Pick the starter documents that match the assessment, filled with the system name. */
export function generateDocs(a: Assessment): GeneratedDoc[] {
  const docs: GeneratedDoc[] = [];
  const ids = new Set([...a.obligations, ...a.transparencyObligations].map((o) => o.id));
  const highProvider = ids.has("HR-P-11");
  const fria = ids.has("HR-D-27");
  const hasTransparency = a.transparencyObligations.length > 0;

  if (highProvider) {
    docs.push({ filename: "annex-iv-technical-documentation.md", content: annexIV(a) + FOOTER });
    docs.push({ filename: "eu-declaration-of-conformity.md", content: declaration(a) + FOOTER });
    docs.push({ filename: "risk-management-summary.md", content: riskManagement(a) + FOOTER });
  }
  if (fria) docs.push({ filename: "fundamental-rights-impact-assessment.md", content: friaDoc(a) + FOOTER });
  if (hasTransparency) docs.push({ filename: "transparency-notice.md", content: transparencyNotice(a) + FOOTER });
  if (docs.length === 0) docs.push({ filename: "readiness-note.md", content: readinessNote(a) + FOOTER });
  return docs;
}

function annexIV(a: Assessment): string {
  return `# Technical documentation (Annex IV) — ${a.system.name}

## 1. General description
- Intended purpose: [TODO]
- Provider (name, address, contact): [TODO]
- Versions and how they differ: [TODO]
- Hardware/software the system interacts with: [TODO]

## 2. Elements and development process
- Design specifications, system architecture, key design choices: [TODO]
- Data requirements and datasets used (provenance, labelling, curation): [TODO]
- Human-oversight measures built in (Art 14): [TODO]

## 3. Monitoring, functioning and control
- Capabilities, limitations, and expected accuracy metrics: [TODO]
- Foreseeable unintended outcomes and sources of risk: [TODO]
- Input-data specifications: [TODO]

## 4. Risk management system (Art 9)
- Summary: see \`risk-management-summary.md\`.

## 5. Changes through the lifecycle
- Change-management approach and version history: [TODO]

## 6. Standards applied
- Harmonised standards / common specifications relied upon: [TODO]

## 7. EU declaration of conformity
- See \`eu-declaration-of-conformity.md\`.

## 8. Post-market monitoring (Art 72)
- Monitoring plan and data collected in operation: [TODO]`;
}

function declaration(a: Assessment): string {
  return `# EU Declaration of Conformity — ${a.system.name}

1. AI system: ${a.system.name} — [model / type / version TODO]
2. Provider: [TODO name and registered address]
3. This declaration of conformity is issued under the sole responsibility of the provider.
4. Object of the declaration (identification allowing traceability): [TODO]
5. The object described above is in conformity with Regulation (EU) 2024/1689 (the AI Act)[, and with: TODO other Union legislation].
6. References to harmonised standards or common specifications applied: [TODO]
7. Notified body (where a third-party assessment applies): [TODO name, number, certificate]
8. Place and date of issue: [TODO]
9. Name, function and signature: [TODO]`;
}

function riskManagement(a: Assessment): string {
  return `# Risk management summary (Art 9) — ${a.system.name}

- Known and reasonably foreseeable risks to health, safety and fundamental rights: [TODO]
- Risks from reasonably foreseeable misuse: [TODO]
- Risk estimation and evaluation: [TODO]
- Risk-mitigation and control measures adopted: [TODO]
- Residual risk and how it is communicated to deployers: [TODO]
- Testing performed, including against defined metrics and thresholds: [TODO]`;
}

function friaDoc(a: Assessment): string {
  return `# Fundamental Rights Impact Assessment (Art 27) — ${a.system.name}

- Deployer (name, role): [TODO]
- Description of the processes in which the system will be used: [TODO]
- Period and frequency of intended use: [TODO]
- Categories of natural persons and groups likely to be affected: [TODO]
- Specific risks of harm to those groups: [TODO]
- Human-oversight measures to be applied: [TODO]
- Measures to take if risks materialise (governance, complaints, remedies): [TODO]`;
}

const SUGGESTED_TEXT: Record<string, string> = {
  "TR-directInteraction": "“You’re chatting with an AI assistant, not a human.”",
  "TR-syntheticContent": "“This content was generated by AI.” (also apply machine-readable marking of outputs)",
  "TR-deepfake": "“This image/audio/video has been artificially generated or manipulated.”",
  "TR-emotionRecognition": "“This system uses emotion recognition. You are being informed as required by law.”",
  "TR-biometricCategorization": "“This system uses biometric categorisation. You are being informed as required by law.”",
  "TR-publicInterestText": "“This text was generated or manipulated using AI.”",
};

function transparencyNotice(a: Assessment): string {
  const lines = a.transparencyObligations
    .map(
      (o) =>
        `### ${o.title} (${o.article}) — responsibility of the ${o.appliesTo}\n${o.summary}\n\nSuggested wording: ${SUGGESTED_TEXT[o.id] ?? "[TODO]"}`,
    )
    .join("\n\n");
  return `# Transparency notice (Art 50) — ${a.system.name}

The following disclosures apply to this system. Adapt the wording and placement to your user experience.

${lines}`;
}

function readinessNote(a: Assessment): string {
  const tail =
    a.tier === "limited"
      ? "Transparency duties apply — see `transparency-notice.md`."
      : "No mandatory obligations under the Act; voluntary codes of conduct (Art 95) are encouraged.";
  return `# EU AI Act readiness note — ${a.system.name}

Based on the profile provided, this system was assessed as **${a.tier} risk**.

${tail}

Re-run the assessment whenever the system's intended purpose, data, or capabilities change.`;
}
