import type { Assessment } from "../types.js";
import { PENALTIES } from "../knowledge/timeline.js";

/** A shareable Markdown readiness report. */
export function toReport(a: Assessment): string {
  const md: string[] = [];
  md.push(`# EU AI Act readiness report — ${a.system.name}`);
  md.push("");
  md.push(`> **${a.disclaimer}**`);
  md.push("");
  md.push(`- **Assessed:** ${a.assessedAt}`);
  md.push(`- **Role:** ${a.system.role}`);
  md.push(`- **GPAI:** ${a.gpai.isGpai ? `yes${a.gpai.systemicRisk ? " (systemic risk)" : ""}` : "no"}`);
  md.push(`- **Knowledge base:** ${a.kbVersion}`);
  md.push("");

  md.push(`## Risk tier: ${a.tier.toUpperCase()}`);
  md.push("");
  md.push("| Reason | Reference |");
  md.push("| --- | --- |");
  for (const r of a.rationale) md.push(`| ${r.reason} | ${r.citation.article} |`);
  md.push("");
  if (a.tier === "unacceptable") {
    md.push("**This practice is prohibited under Article 5 and must not be placed on the market or put into service.**");
    md.push("");
  }

  if (a.obligations.length > 0) {
    md.push("## Obligations that apply");
    md.push("");
    md.push("| # | Obligation | Article | What it means |");
    md.push("| --- | --- | --- | --- |");
    a.obligations.forEach((o, i) => md.push(`| ${i + 1} | ${o.title} | ${o.article} | ${o.summary} |`));
    md.push("");
  }

  if (a.transparencyObligations.length > 0) {
    md.push("## Transparency duties (Article 50)");
    md.push("");
    md.push("| Duty | Article | Responsible |");
    md.push("| --- | --- | --- |");
    for (const o of a.transparencyObligations) md.push(`| ${o.title} | ${o.article} | ${o.appliesTo} |`);
    md.push("");
  }

  md.push("## Key dates");
  md.push("");
  md.push("| Date | Milestone | Status |");
  md.push("| --- | --- | --- |");
  for (const t of a.timeline) md.push(`| ${t.date} | ${t.milestone} | ${t.status} |`);
  md.push("");

  md.push("## Penalties");
  md.push("");
  md.push("| Violation | Maximum |");
  md.push("| --- | --- |");
  for (const pen of PENALTIES) md.push(`| ${pen.violation} | ${pen.max} |`);
  md.push("");

  md.push("---");
  md.push("_Generated by [sentinel-act](https://github.com/aadityaparab/sentinel-act), part of the Sentinel Stack family. Informational only — not legal advice._");
  return md.join("\n");
}
